# Visualize
RENDER = True
SAVE_Q_TABLE = False
LEARNING_RATE = 0.0
DEBUG = True
INITIAL_EPSILON = 0

# Train
# DEBUG = False
# RENDER = False
# SAVE_Q_TABLE = True
# LEARNING_RATE = 0.05
# INITIAL_EPSILON = 1.0

DEBUG_UPDATE = 10

N_EPISODES = 100_000
FINAL_EPSILON = 0.05
EPSILON_DECAY = (INITIAL_EPSILON - FINAL_EPSILON) / (N_EPISODES * 0.7)
FINAL_EPSILON = 0.1
DISCOUNT_FACTOR = 0.95

FILE_NAME = "q_table.npy"
