RENDER = True
DEBUG = True
DEBUG_UPDATE = 10

N_EPISODES = 10_000
LEARNING_RATE = 0.001
INITIAL_EPSILON = 1.0
EPSILON_DECAY = INITIAL_EPSILON / (N_EPISODES / 2)
FINAL_EPSILON = 0.1
DISCOUNT_FACTOR = 0.95

FILE_NAME = "q_table.npy"
